### ISSUE TITLE
The configuration of the Items short view does not work correctly in DSpace-CRIS release 2024.02.00

### ISSUE THREAD

**Issue by OrdinaryGitUser** [4Science/dspace-angular#109]
I have configured a Items short view as described in the manual, but the short view does not show all the metadata even when it is present in the Item.

1. Add the following to config.*.yml.
```
searchResult:
  additionalMetadataFields:
    - entityType: publication
      metadataConfiguration:
        - name: dc.type
          rendering: text
          label: Type
        - name: dc.relation.journal
          rendering: crisref
          label: Journal
        - name: oaire.citation.volume
          rendering: text
          label: Volume
        - name: oaire.citation.issue
          rendering: text
          label: Issue
        - name: oaire.citation.startPage
          rendering: text
          label: Start page
        - name: oaire.citation.endPage
          rendering: text
          label: End Page
        - name: dc.identifier.doi
          rendering: identifier.doi
          label: Doi
    - entityType: journal
      metadataConfiguration:
        - name: dc.relation.issn
          rendering: text
          label: ISSN         
    - entityType: fallback # used for other entity types
      metadataConfiguration:
        - name: dc.identifier.doi
          rendering: identifier.doi
          label: DOI
```

The Items short view should display all the metadata available in the Item as it was in previous versions.

What it looked like in DSpace-CRIS 2023.02.00
![Image](https://github.com/user-attachments/assets/37645cf6-79b1-4ce2-be53-ff7586a867be)

And in DSpace-CRIS version 2024.02.00
![Image](https://github.com/user-attachments/assets/1afb2e38-b77a-45ae-8d1d-91b99d52080d)
